# Generated by Django 4.1.7 on 2023-02-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="food_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_item",
                to="product.foodimage",
            ),
        ),
    ]
