# Generated by Django 4.1.7 on 2023-02-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_category_remove_fooditem_food_item_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="fooditem",
            old_name="name",
            new_name="size",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="food_image",
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("food_image", models.ImageField(upload_to="static/")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fooditem",
            name="food",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.food",
            ),
        ),
    ]
