# Generated by Django 4.1.7 on 2024-01-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_marketname_delete_marketplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="location",
            field=models.ForeignKey(
                max_length=500,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.location",
            ),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="market_name",
            field=models.ForeignKey(
                max_length=500,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.marketname",
            ),
        ),
    ]
