# Generated by Django 4.2.9 on 2024-01-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_fooditem_location_alter_fooditem_market_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketname",
            old_name="location_name",
            new_name="location",
        ),
    ]
