# Generated by Django 4.1.7 on 2024-01-12 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="password2",
        ),
    ]
